### ISSUE TITLE
Load a formatted Google GGannt csv or json file directly

### ISSUE THREAD

**Issue by WesIngwersen** [WesIngwersen/prodgannt#2]
Write the formatted Gannt out to either JSON (similar to current array) or to csv and enable the user to load that file to render the Gannt.

**Comment by oftheheadland** [comment]
Hey @WesIngwersen, the text appearing on the page is intentional and just a tool for debugging. It can be easily removed. As for issues with the code itself, you'll have to check with Sarah Cashman to find out who will be taking over this project. Tomorrow is my last day at ERG. It's been a pleasure working with you Wes!
